apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hz6y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hz6y
    app.kubernetes.io/part-of: ci10t-786-0092-app
  name: devfile-sample-hz6y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hz6y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hz6y
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0092-tenant/ci10t-786-0092-app/devfile-sample-hz6y@sha256:d28d6c0587277b38c40bbcd33505fa2f7fe1bcf5f2b3eddd74aaf00eb3f3eb45
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
